export interface ElementData {
	number: number;
	symbol: string;
	name: string;
	mass: number;
	category: ElementCategory;
	row: number; // 1 to 10 (8 & 9 reserved for Lanthanides/Actinides)
	col: number; // 1 to 18
	electronegativity: number | null; // Pauling scale
	density: number | null; // g/cm³
	melt: number | null; // Kelvin
	boil: number | null; // Kelvin
	discoveryYear: number | string;
	electronConfig: string;
	summary: string;
}

export type ElementCategory =
	| 'reactive-nonmetal'
	| 'noble-gas'
	| 'alkali-metal'
	| 'alkaline-earth'
	| 'metalloid'
	| 'post-transition'
	| 'transition'
	| 'lanthanide'
	| 'actinide'
	| 'unknown';

export interface CategoryInfo {
	id: ElementCategory;
	label: string;
	color: string;
	border: string;
	text: string;
}

export const CATEGORIES: Record<ElementCategory, CategoryInfo> = {
	'reactive-nonmetal': {
		id: 'reactive-nonmetal',
		label: 'Reactive Nonmetals',
		color: 'bg-emerald-500/20',
		border: 'border-emerald-500/40',
		text: 'text-emerald-400'
	},
	'noble-gas': {
		id: 'noble-gas',
		label: 'Noble Gases',
		color: 'bg-purple-500/20',
		border: 'border-purple-500/40',
		text: 'text-purple-300'
	},
	'alkali-metal': {
		id: 'alkali-metal',
		label: 'Alkali Metals',
		color: 'bg-rose-500/20',
		border: 'border-rose-500/40',
		text: 'text-rose-400'
	},
	'alkaline-earth': {
		id: 'alkaline-earth',
		label: 'Alkaline Earth',
		color: 'bg-amber-500/20',
		border: 'border-amber-500/40',
		text: 'text-amber-400'
	},
	metalloid: {
		id: 'metalloid',
		label: 'Metalloids',
		color: 'bg-teal-500/20',
		border: 'border-teal-500/40',
		text: 'text-teal-300'
	},
	'post-transition': {
		id: 'post-transition',
		label: 'Post-Transition',
		color: 'bg-blue-500/20',
		border: 'border-blue-500/40',
		text: 'text-blue-400'
	},
	transition: {
		id: 'transition',
		label: 'Transition Metals',
		color: 'bg-indigo-500/20',
		border: 'border-indigo-500/40',
		text: 'text-indigo-300'
	},
	lanthanide: {
		id: 'lanthanide',
		label: 'Lanthanides',
		color: 'bg-sky-500/20',
		border: 'border-sky-500/40',
		text: 'text-sky-300'
	},
	actinide: {
		id: 'actinide',
		label: 'Actinides',
		color: 'bg-pink-500/20',
		border: 'border-pink-500/40',
		text: 'text-pink-300'
	},
	unknown: {
		id: 'unknown',
		label: 'Unknown Properties',
		color: 'bg-white/10',
		border: 'border-white/20',
		text: 'text-white/50'
	}
};

export type HeatmapMetric = 'mass' | 'electronegativity' | 'density' | 'melt' | 'boil';

export const HEATMAP_METRICS: {
	id: HeatmapMetric;
	label: string;
	unit: string;
	min: number;
	max: number;
}[] = [
	{ id: 'mass', label: 'Atomic Mass', unit: 'u', min: 1.008, max: 294 },
	{ id: 'electronegativity', label: 'Electronegativity', unit: 'Pauling', min: 0.7, max: 3.98 },
	{ id: 'density', label: 'Density', unit: 'g/cm³', min: 0.000089, max: 22.59 },
	{ id: 'melt', label: 'Melting Point', unit: 'K', min: 0.95, max: 3950 },
	{ id: 'boil', label: 'Boiling Point', unit: 'K', min: 4.22, max: 5869 }
];

export function getElementState(
	el: ElementData,
	tempK: number
): 'solid' | 'liquid' | 'gas' | 'unknown' {
	if (el.melt === null || el.boil === null) return 'unknown';
	if (tempK < el.melt) return 'solid';
	if (tempK < el.boil) return 'liquid';
	return 'gas';
}

export function getHeatmapOpacity(val: number | null, min: number, max: number): number {
	if (val === null) return 0.05;
	const ratio = (val - min) / (max - min);
	return Math.max(0.1, Math.min(1, ratio));
}

export const ELEMENTS: ElementData[] = [
	{
		number: 1,
		symbol: 'H',
		name: 'Hydrogen',
		mass: 1.008,
		category: 'reactive-nonmetal',
		row: 1,
		col: 1,
		electronegativity: 2.2,
		density: 0.00008988,
		melt: 13.99,
		boil: 20.271,
		discoveryYear: 1766,
		electronConfig: '1s¹',
		summary: 'The lightest and most abundant chemical substance in the Universe.'
	},
	{
		number: 2,
		symbol: 'He',
		name: 'Helium',
		mass: 4.0026,
		category: 'noble-gas',
		row: 1,
		col: 18,
		electronegativity: null,
		density: 0.0001785,
		melt: 0.95,
		boil: 4.222,
		discoveryYear: 1868,
		electronConfig: '1s²',
		summary: 'Colorless, odorless, tasteless, non-toxic, inert, monatomic gas.'
	},
	{
		number: 3,
		symbol: 'Li',
		name: 'Lithium',
		mass: 6.94,
		category: 'alkali-metal',
		row: 2,
		col: 1,
		electronegativity: 0.98,
		density: 0.534,
		melt: 453.65,
		boil: 1603,
		discoveryYear: 1817,
		electronConfig: '[He] 2s¹',
		summary: 'Soft, silvery-white alkali metal. The least dense solid element.'
	},
	{
		number: 4,
		symbol: 'Be',
		name: 'Beryllium',
		mass: 9.0122,
		category: 'alkaline-earth',
		row: 2,
		col: 2,
		electronegativity: 1.57,
		density: 1.85,
		melt: 1560,
		boil: 2742,
		discoveryYear: 1798,
		electronConfig: '[He] 2s²',
		summary: 'Relatively rare in the universe, formed when cosmic rays strike atomic nuclei.'
	},
	{
		number: 5,
		symbol: 'B',
		name: 'Boron',
		mass: 10.81,
		category: 'metalloid',
		row: 2,
		col: 13,
		electronegativity: 2.04,
		density: 2.34,
		melt: 2349,
		boil: 4200,
		discoveryYear: 1808,
		electronConfig: '[He] 2s² 2p¹',
		summary: 'Low-abundance metalloid produced entirely by cosmic ray spallation.'
	},
	{
		number: 6,
		symbol: 'C',
		name: 'Carbon',
		mass: 12.011,
		category: 'reactive-nonmetal',
		row: 2,
		col: 14,
		electronegativity: 2.55,
		density: 2.267,
		melt: 3823,
		boil: 4098,
		discoveryYear: 'Ancient',
		electronConfig: '[He] 2s² 2p²',
		summary: 'Tetravalent nonmetal that forms the backbone of all known organic life.'
	},
	{
		number: 7,
		symbol: 'N',
		name: 'Nitrogen',
		mass: 14.007,
		category: 'reactive-nonmetal',
		row: 2,
		col: 15,
		electronegativity: 3.04,
		density: 0.0012506,
		melt: 63.15,
		boil: 77.355,
		discoveryYear: 1772,
		electronConfig: '[He] 2s² 2p³',
		summary: "Makes up about 78% of Earth's atmosphere as a diatomic gas."
	},
	{
		number: 8,
		symbol: 'O',
		name: 'Oxygen',
		mass: 15.999,
		category: 'reactive-nonmetal',
		row: 2,
		col: 16,
		electronegativity: 3.44,
		density: 0.001429,
		melt: 54.36,
		boil: 90.188,
		discoveryYear: 1774,
		electronConfig: '[He] 2s² 2p⁴',
		summary: 'Highly reactive nonmetal and oxidizing agent that forms oxides easily.'
	},
	{
		number: 9,
		symbol: 'F',
		name: 'Fluorine',
		mass: 18.998,
		category: 'reactive-nonmetal',
		row: 2,
		col: 17,
		electronegativity: 3.98,
		density: 0.001696,
		melt: 53.48,
		boil: 85.03,
		discoveryYear: 1886,
		electronConfig: '[He] 2s² 2p⁵',
		summary: 'Extremely toxic and reactive halogen gas, the most electronegative element.'
	},
	{
		number: 10,
		symbol: 'Ne',
		name: 'Neon',
		mass: 20.18,
		category: 'noble-gas',
		row: 2,
		col: 18,
		electronegativity: null,
		density: 0.0009002,
		melt: 24.56,
		boil: 27.104,
		discoveryYear: 1898,
		electronConfig: '[He] 2s² 2p⁶',
		summary: 'Noble gas glowing reddish-orange in high-voltage electrical discharge.'
	},
	{
		number: 11,
		symbol: 'Na',
		name: 'Sodium',
		mass: 22.99,
		category: 'alkali-metal',
		row: 3,
		col: 1,
		electronegativity: 0.93,
		density: 0.968,
		melt: 370.944,
		boil: 1156.09,
		discoveryYear: 1807,
		electronConfig: '[Ne] 3s¹',
		summary: 'Soft, silvery-white, highly reactive alkali metal.'
	},
	{
		number: 12,
		symbol: 'Mg',
		name: 'Magnesium',
		mass: 24.305,
		category: 'alkaline-earth',
		row: 3,
		col: 2,
		electronegativity: 1.31,
		density: 1.738,
		melt: 923,
		boil: 1363,
		discoveryYear: 1755,
		electronConfig: '[Ne] 3s²',
		summary: 'Shiny gray solid; structural metal essential for cellular biochemistry.'
	},
	{
		number: 13,
		symbol: 'Al',
		name: 'Aluminium',
		mass: 26.982,
		category: 'post-transition',
		row: 3,
		col: 13,
		electronegativity: 1.61,
		density: 2.7,
		melt: 933.47,
		boil: 2743,
		discoveryYear: 1825,
		electronConfig: '[Ne] 3s² 3p¹',
		summary: 'Low density metal with high corrosion resistance and thermal conductivity.'
	},
	{
		number: 14,
		symbol: 'Si',
		name: 'Silicon',
		mass: 28.085,
		category: 'metalloid',
		row: 3,
		col: 14,
		electronegativity: 1.9,
		density: 2.329,
		melt: 1687,
		boil: 3538,
		discoveryYear: 1824,
		electronConfig: '[Ne] 3s² 3p²',
		summary: 'Hard, brittle crystalline metalloid widely used as semiconductor.'
	},
	{
		number: 15,
		symbol: 'P',
		name: 'Phosphorus',
		mass: 30.974,
		category: 'reactive-nonmetal',
		row: 3,
		col: 15,
		electronegativity: 2.19,
		density: 1.823,
		melt: 317.3,
		boil: 553.7,
		discoveryYear: 1669,
		electronConfig: '[Ne] 3s² 3p³',
		summary: 'Essential for life, existing in white, red, and violet allotropes.'
	},
	{
		number: 16,
		symbol: 'S',
		name: 'Sulfur',
		mass: 32.06,
		category: 'reactive-nonmetal',
		row: 3,
		col: 16,
		electronegativity: 2.58,
		density: 2.07,
		melt: 388.36,
		boil: 717.8,
		discoveryYear: 'Ancient',
		electronConfig: '[Ne] 3s² 3p⁴',
		summary: 'Abundant, multivalent nonmetal; bright yellow crystalline solid at room temp.'
	},
	{
		number: 17,
		symbol: 'Cl',
		name: 'Chlorine',
		mass: 35.45,
		category: 'reactive-nonmetal',
		row: 3,
		col: 17,
		electronegativity: 3.16,
		density: 0.0032,
		melt: 171.6,
		boil: 239.11,
		discoveryYear: 1774,
		electronConfig: '[Ne] 3s² 3p⁵',
		summary: 'Yellow-green halogen gas used extensively in water purification.'
	},
	{
		number: 18,
		symbol: 'Ar',
		name: 'Argon',
		mass: 39.948,
		category: 'noble-gas',
		row: 3,
		col: 18,
		electronegativity: null,
		density: 0.001784,
		melt: 83.81,
		boil: 87.302,
		discoveryYear: 1894,
		electronConfig: '[Ne] 3s² 3p⁶',
		summary: "Third-most abundant gas in Earth's atmosphere."
	},
	{
		number: 19,
		symbol: 'K',
		name: 'Potassium',
		mass: 39.098,
		category: 'alkali-metal',
		row: 4,
		col: 1,
		electronegativity: 0.82,
		density: 0.89,
		melt: 336.7,
		boil: 1032,
		discoveryYear: 1807,
		electronConfig: '[Ar] 4s¹',
		summary: 'Silvery alkali metal that reacts vigorously with water.'
	},
	{
		number: 20,
		symbol: 'Ca',
		name: 'Calcium',
		mass: 40.078,
		category: 'alkaline-earth',
		row: 4,
		col: 2,
		electronegativity: 1.0,
		density: 1.55,
		melt: 1115,
		boil: 1757,
		discoveryYear: 1808,
		electronConfig: '[Ar] 4s²',
		summary: 'Essential metal for living organisms, bone structure, and neurotransmission.'
	},
	{
		number: 21,
		symbol: 'Sc',
		name: 'Scandium',
		mass: 44.956,
		category: 'transition',
		row: 4,
		col: 3,
		electronegativity: 1.36,
		density: 2.985,
		melt: 1814,
		boil: 3109,
		discoveryYear: 1879,
		electronConfig: '[Ar] 3d¹ 4s²',
		summary: 'Silvery-white d-block transition metal often classified as rare-earth.'
	},
	{
		number: 22,
		symbol: 'Ti',
		name: 'Titanium',
		mass: 47.867,
		category: 'transition',
		row: 4,
		col: 4,
		electronegativity: 1.54,
		density: 4.506,
		melt: 1941,
		boil: 3560,
		discoveryYear: 1791,
		electronConfig: '[Ar] 3d² 4s²',
		summary:
			'Lustrous transition metal with high strength-to-weight ratio and corrosion resistance.'
	},
	{
		number: 23,
		symbol: 'V',
		name: 'Vanadium',
		mass: 50.942,
		category: 'transition',
		row: 4,
		col: 5,
		electronegativity: 1.63,
		density: 6.11,
		melt: 2183,
		boil: 3680,
		discoveryYear: 1801,
		electronConfig: '[Ar] 3d³ 4s²',
		summary: 'Hard, silvery-gray, ductile transition metal used in specialized steel alloys.'
	},
	{
		number: 24,
		symbol: 'Cr',
		name: 'Chromium',
		mass: 51.996,
		category: 'transition',
		row: 4,
		col: 6,
		electronegativity: 1.66,
		density: 7.19,
		melt: 2180,
		boil: 2944,
		discoveryYear: 1797,
		electronConfig: '[Ar] 3d⁵ 4s¹',
		summary: 'Steely-gray, lustrous, hard, and brittle transition metal with high polish.'
	},
	{
		number: 25,
		symbol: 'Mn',
		name: 'Manganese',
		mass: 54.938,
		category: 'transition',
		row: 4,
		col: 7,
		electronegativity: 1.55,
		density: 7.21,
		melt: 1519,
		boil: 2334,
		discoveryYear: 1774,
		electronConfig: '[Ar] 3d⁵ 4s²',
		summary: 'Hard brittle metal, foundational in industrial steel production.'
	},
	{
		number: 26,
		symbol: 'Fe',
		name: 'Iron',
		mass: 55.845,
		category: 'transition',
		row: 4,
		col: 8,
		electronegativity: 1.83,
		density: 7.874,
		melt: 1811,
		boil: 3134,
		discoveryYear: 'Ancient',
		electronConfig: '[Ar] 3d⁶ 4s²',
		summary: "Most common element on Earth by mass, forming much of Earth's outer & inner core."
	},
	{
		number: 27,
		symbol: 'Co',
		name: 'Cobalt',
		mass: 58.933,
		category: 'transition',
		row: 4,
		col: 9,
		electronegativity: 1.88,
		density: 8.9,
		melt: 1768,
		boil: 3200,
		discoveryYear: 1735,
		electronConfig: '[Ar] 3d⁷ 4s²',
		summary: 'Ferromagnetic transition metal used in superalloys and lithium-ion batteries.'
	},
	{
		number: 28,
		symbol: 'Ni',
		name: 'Nickel',
		mass: 58.693,
		category: 'transition',
		row: 4,
		col: 10,
		electronegativity: 1.91,
		density: 8.908,
		melt: 1728,
		boil: 3003,
		discoveryYear: 1751,
		electronConfig: '[Ar] 3d⁸ 4s²',
		summary: 'Silvery-white lustrous metal with a slight golden tinge; corrosion resistant.'
	},
	{
		number: 29,
		symbol: 'Cu',
		name: 'Copper',
		mass: 63.546,
		category: 'transition',
		row: 4,
		col: 11,
		electronegativity: 1.9,
		density: 8.96,
		melt: 1357.77,
		boil: 2835,
		discoveryYear: 'Ancient',
		electronConfig: '[Ar] 3d¹⁰ 4s¹',
		summary:
			'Soft, malleable, and ductile metal with very high thermal and electrical conductivity.'
	},
	{
		number: 30,
		symbol: 'Zn',
		name: 'Zinc',
		mass: 65.38,
		category: 'transition',
		row: 4,
		col: 12,
		electronegativity: 1.65,
		density: 7.14,
		melt: 692.68,
		boil: 1180,
		discoveryYear: 1746,
		electronConfig: '[Ar] 3d¹⁰ 4s²',
		summary: 'Slightly brittle metal at room temp, widely used for galvanizing steel.'
	},
	{
		number: 31,
		symbol: 'Ga',
		name: 'Gallium',
		mass: 69.723,
		category: 'post-transition',
		row: 4,
		col: 13,
		electronegativity: 1.81,
		density: 5.91,
		melt: 302.91,
		boil: 2673,
		discoveryYear: 1875,
		electronConfig: '[Ar] 3d¹⁰ 4s² 4p¹',
		summary: 'Melts near room temperature (29.76 °C), liquefying in the human hand.'
	},
	{
		number: 32,
		symbol: 'Ge',
		name: 'Germanium',
		mass: 72.63,
		category: 'metalloid',
		row: 4,
		col: 14,
		electronegativity: 2.01,
		density: 5.323,
		melt: 1211.4,
		boil: 3106,
		discoveryYear: 1886,
		electronConfig: '[Ar] 3d¹⁰ 4s² 4p²',
		summary: 'Lustrous, hard, grayish-white metalloid chemically similar to tin and silicon.'
	},
	{
		number: 33,
		symbol: 'As',
		name: 'Arsenic',
		mass: 74.922,
		category: 'metalloid',
		row: 4,
		col: 15,
		electronegativity: 2.18,
		density: 5.727,
		melt: 1090,
		boil: 887,
		discoveryYear: 1250,
		electronConfig: '[Ar] 3d¹⁰ 4s² 4p³',
		summary: 'Infamous poisonous metalloid occurring in many minerals.'
	},
	{
		number: 34,
		symbol: 'Se',
		name: 'Selenium',
		mass: 78.971,
		category: 'reactive-nonmetal',
		row: 4,
		col: 16,
		electronegativity: 2.55,
		density: 4.81,
		melt: 494,
		boil: 958,
		discoveryYear: 1817,
		electronConfig: '[Ar] 3d¹⁰ 4s² 4p⁴',
		summary: 'Photoconductive nonmetal with applications in photocells and solar cells.'
	},
	{
		number: 35,
		symbol: 'Br',
		name: 'Bromine',
		mass: 79.904,
		category: 'reactive-nonmetal',
		row: 4,
		col: 17,
		electronegativity: 2.96,
		density: 3.1028,
		melt: 265.8,
		boil: 332.0,
		discoveryYear: 1826,
		electronConfig: '[Ar] 3d¹⁰ 4s² 4p⁵',
		summary: 'Fuming red-brown liquid at room temperature, evaporated easily.'
	},
	{
		number: 36,
		symbol: 'Kr',
		name: 'Krypton',
		mass: 83.798,
		category: 'noble-gas',
		row: 4,
		col: 18,
		electronegativity: 3.0,
		density: 0.003749,
		melt: 115.79,
		boil: 119.93,
		discoveryYear: 1898,
		electronConfig: '[Ar] 3d¹⁰ 4s² 4p⁶',
		summary: 'Colorless, odorless noble gas used in energy-efficient fluorescent lights.'
	},
	{
		number: 37,
		symbol: 'Rb',
		name: 'Rubidium',
		mass: 85.468,
		category: 'alkali-metal',
		row: 5,
		col: 1,
		electronegativity: 0.82,
		density: 1.532,
		melt: 312.46,
		boil: 961,
		discoveryYear: 1861,
		electronConfig: '[Kr] 5s¹',
		summary: 'Soft, silvery-white alkali metal that ignites spontaneously in air.'
	},
	{
		number: 38,
		symbol: 'Sr',
		name: 'Strontium',
		mass: 87.62,
		category: 'alkaline-earth',
		row: 5,
		col: 2,
		electronegativity: 0.95,
		density: 2.64,
		melt: 1050,
		boil: 1655,
		discoveryYear: 1790,
		electronConfig: '[Kr] 5s²',
		summary: 'Soft, yellowish alkaline earth metal giving brilliant red color to fireworks.'
	},
	{
		number: 39,
		symbol: 'Y',
		name: 'Yttrium',
		mass: 88.906,
		category: 'transition',
		row: 5,
		col: 3,
		electronegativity: 1.22,
		density: 4.472,
		melt: 1799,
		boil: 3609,
		discoveryYear: 1794,
		electronConfig: '[Kr] 4d¹ 5s²',
		summary: 'Silvery metallic transition metal used in phosphors for LEDs and lasers.'
	},
	{
		number: 40,
		symbol: 'Zr',
		name: 'Zirconium',
		mass: 91.224,
		category: 'transition',
		row: 5,
		col: 4,
		electronegativity: 1.33,
		density: 6.52,
		melt: 2128,
		boil: 4682,
		discoveryYear: 1789,
		electronConfig: '[Kr] 4d² 5s²',
		summary: 'Lustrous, grey-white, strong transition metal resistant to corrosion.'
	},
	{
		number: 41,
		symbol: 'Nb',
		name: 'Niobium',
		mass: 92.906,
		category: 'transition',
		row: 5,
		col: 5,
		electronegativity: 1.6,
		density: 8.57,
		melt: 2750,
		boil: 5017,
		discoveryYear: 1801,
		electronConfig: '[Kr] 4d⁴ 5s¹',
		summary: 'Ductile transition metal essential in superconducting alloys.'
	},
	{
		number: 42,
		symbol: 'Mo',
		name: 'Molybdenum',
		mass: 95.95,
		category: 'transition',
		row: 5,
		col: 6,
		electronegativity: 2.16,
		density: 10.28,
		melt: 2896,
		boil: 4912,
		discoveryYear: 1778,
		electronConfig: '[Kr] 4d⁵ 5s¹',
		summary: 'High-melting metal forming extremely hard steel alloys.'
	},
	{
		number: 43,
		symbol: 'Tc',
		name: 'Technetium',
		mass: 98,
		category: 'transition',
		row: 5,
		col: 7,
		electronegativity: 1.9,
		density: 11,
		melt: 2430,
		boil: 4538,
		discoveryYear: 1937,
		electronConfig: '[Kr] 4d⁵ 5s²',
		summary: 'Lightest element whose isotopes are all radioactive.'
	},
	{
		number: 44,
		symbol: 'Ru',
		name: 'Ruthenium',
		mass: 101.07,
		category: 'transition',
		row: 5,
		col: 8,
		electronegativity: 2.2,
		density: 12.45,
		melt: 2607,
		boil: 4423,
		discoveryYear: 1844,
		electronConfig: '[Kr] 4d⁷ 5s¹',
		summary: 'Rare transition metal belonging to platinum group metals.'
	},
	{
		number: 45,
		symbol: 'Rh',
		name: 'Rhodium',
		mass: 102.91,
		category: 'transition',
		row: 5,
		col: 9,
		electronegativity: 2.28,
		density: 12.41,
		melt: 2237,
		boil: 3968,
		discoveryYear: 1803,
		electronConfig: '[Kr] 4d⁸ 5s¹',
		summary: 'Rare, silvery-white, hard, corrosion-resistant noble metal.'
	},
	{
		number: 46,
		symbol: 'Pd',
		name: 'Palladium',
		mass: 106.42,
		category: 'transition',
		row: 5,
		col: 10,
		electronegativity: 2.2,
		density: 12.023,
		melt: 1828.05,
		boil: 3236,
		discoveryYear: 1803,
		electronConfig: '[Kr] 4d¹⁰',
		summary: 'Rare catalytic metal capable of absorbing up to 900 times its volume in hydrogen.'
	},
	{
		number: 47,
		symbol: 'Ag',
		name: 'Silver',
		mass: 107.87,
		category: 'transition',
		row: 5,
		col: 11,
		electronegativity: 1.93,
		density: 10.49,
		melt: 1234.93,
		boil: 2435,
		discoveryYear: 'Ancient',
		electronConfig: '[Kr] 4d¹⁰ 5s¹',
		summary: 'Highest electrical conductivity, thermal conductivity, and reflectivity of any metal.'
	},
	{
		number: 48,
		symbol: 'Cd',
		name: 'Cadmium',
		mass: 112.41,
		category: 'transition',
		row: 5,
		col: 12,
		electronegativity: 1.69,
		density: 8.65,
		melt: 594.22,
		boil: 1040,
		discoveryYear: 1817,
		electronConfig: '[Kr] 4d¹⁰ 5s²',
		summary: 'Soft, malleable bluish-white toxic metal.'
	},
	{
		number: 49,
		symbol: 'In',
		name: 'Indium',
		mass: 114.82,
		category: 'post-transition',
		row: 5,
		col: 13,
		electronegativity: 1.78,
		density: 7.31,
		melt: 429.75,
		boil: 2345,
		discoveryYear: 1863,
		electronConfig: '[Kr] 4d¹⁰ 5s² 5p¹',
		summary: 'Very soft post-transition metal essential for Indium Tin Oxide (ITO) touchscreens.'
	},
	{
		number: 50,
		symbol: 'Sn',
		name: 'Tin',
		mass: 118.71,
		category: 'post-transition',
		row: 5,
		col: 14,
		electronegativity: 1.96,
		density: 7.287,
		melt: 505.08,
		boil: 2875,
		discoveryYear: 'Ancient',
		electronConfig: '[Kr] 4d¹⁰ 5s² 5p²',
		summary: 'Silvery metal with faint yellow hue, resists corrosion well.'
	},
	{
		number: 51,
		symbol: 'Sb',
		name: 'Antimony',
		mass: 121.76,
		category: 'metalloid',
		row: 5,
		col: 15,
		electronegativity: 2.05,
		density: 6.697,
		melt: 903.78,
		boil: 1908,
		discoveryYear: 'Ancient',
		electronConfig: '[Kr] 4d¹⁰ 5s² 5p³',
		summary: 'Lustrous gray metalloid used in flame retardants and microelectronics.'
	},
	{
		number: 52,
		symbol: 'Te',
		name: 'Tellurium',
		mass: 127.6,
		category: 'metalloid',
		row: 5,
		col: 16,
		electronegativity: 2.1,
		density: 6.24,
		melt: 722.66,
		boil: 1261,
		discoveryYear: 1782,
		electronConfig: '[Kr] 4d¹⁰ 5s² 5p⁴',
		summary: 'Brittle, mildly toxic, rare metalloid related to selenium and sulfur.'
	},
	{
		number: 53,
		symbol: 'I',
		name: 'Iodine',
		mass: 126.9,
		category: 'reactive-nonmetal',
		row: 5,
		col: 17,
		electronegativity: 2.66,
		density: 4.933,
		melt: 386.85,
		boil: 457.4,
		discoveryYear: 1811,
		electronConfig: '[Kr] 4d¹⁰ 5s² 5p⁵',
		summary: 'Lustrous purple-black nonmetal halogen required by thyroid metabolism.'
	},
	{
		number: 54,
		symbol: 'Xe',
		name: 'Xenon',
		mass: 131.29,
		category: 'noble-gas',
		row: 5,
		col: 18,
		electronegativity: 2.6,
		density: 0.005894,
		melt: 161.4,
		boil: 165.051,
		discoveryYear: 1898,
		electronConfig: '[Kr] 4d¹⁰ 5s² 5p⁶',
		summary: 'Heavy noble gas used in specialized arc lamps and ion propulsion engines.'
	},
	{
		number: 55,
		symbol: 'Cs',
		name: 'Caesium',
		mass: 132.91,
		category: 'alkali-metal',
		row: 6,
		col: 1,
		electronegativity: 0.79,
		density: 1.93,
		melt: 301.7,
		boil: 944,
		discoveryYear: 1860,
		electronConfig: '[Xe] 6s¹',
		summary: 'Soft, silvery-gold alkali metal; basis for official atomic time standard.'
	},
	{
		number: 56,
		symbol: 'Ba',
		name: 'Barium',
		mass: 137.33,
		category: 'alkaline-earth',
		row: 6,
		col: 2,
		electronegativity: 0.89,
		density: 3.51,
		melt: 1000,
		boil: 2170,
		discoveryYear: 1808,
		electronConfig: '[Xe] 6s²',
		summary: 'Soft, silvery alkaline earth metal with high chemical reactivity.'
	},
	{
		number: 57,
		symbol: 'La',
		name: 'Lanthanum',
		mass: 138.91,
		category: 'lanthanide',
		row: 8,
		col: 3,
		electronegativity: 1.1,
		density: 6.162,
		melt: 1193,
		boil: 3737,
		discoveryYear: 1839,
		electronConfig: '[Xe] 5d¹ 6s²',
		summary: 'Soft, ductile, silvery rare earth metal giving its name to the lanthanides.'
	},
	{
		number: 58,
		symbol: 'Ce',
		name: 'Cerium',
		mass: 140.12,
		category: 'lanthanide',
		row: 8,
		col: 4,
		electronegativity: 1.12,
		density: 6.77,
		melt: 1068,
		boil: 3716,
		discoveryYear: 1803,
		electronConfig: '[Xe] 4f¹ 5d¹ 6s²',
		summary: 'Most abundant lanthanide metal, used in lighter flints and glass polishing.'
	},
	{
		number: 59,
		symbol: 'Pr',
		name: 'Praseodymium',
		mass: 140.91,
		category: 'lanthanide',
		row: 8,
		col: 5,
		electronegativity: 1.13,
		density: 6.77,
		melt: 1208,
		boil: 3793,
		discoveryYear: 1885,
		electronConfig: '[Xe] 4f³ 6s²',
		summary: 'Soft, silvery metal used in high-strength magnets and yellow glass filters.'
	},
	{
		number: 60,
		symbol: 'Nd',
		name: 'Neodymium',
		mass: 144.24,
		category: 'lanthanide',
		row: 8,
		col: 6,
		electronegativity: 1.14,
		density: 7.01,
		melt: 1297,
		boil: 3347,
		discoveryYear: 1885,
		electronConfig: '[Xe] 4f⁴ 6s²',
		summary: 'Essential for powerful neodymium magnets used in electric motors and speakers.'
	},
	{
		number: 61,
		symbol: 'Pm',
		name: 'Promethium',
		mass: 145,
		category: 'lanthanide',
		row: 8,
		col: 7,
		electronegativity: 1.13,
		density: 7.26,
		melt: 1315,
		boil: 3273,
		discoveryYear: 1945,
		electronConfig: '[Xe] 4f⁵ 6s²',
		summary: 'Radioactive rare earth metal used in atomic batteries.'
	},
	{
		number: 62,
		symbol: 'Sm',
		name: 'Samarium',
		mass: 150.36,
		category: 'lanthanide',
		row: 8,
		col: 8,
		electronegativity: 1.17,
		density: 7.52,
		melt: 1345,
		boil: 2067,
		discoveryYear: 1879,
		electronConfig: '[Xe] 4f⁶ 6s²',
		summary: 'Moderately hard metal used in high-temperature Samarium-Cobalt magnets.'
	},
	{
		number: 63,
		symbol: 'Eu',
		name: 'Europium',
		mass: 151.96,
		category: 'lanthanide',
		row: 8,
		col: 9,
		electronegativity: 1.2,
		density: 5.244,
		melt: 1099,
		boil: 1802,
		discoveryYear: 1901,
		electronConfig: '[Xe] 4f⁷ 6s²',
		summary: 'Most reactive lanthanide metal, producing vivid red phosphors in displays.'
	},
	{
		number: 64,
		symbol: 'Gd',
		name: 'Gadolinium',
		mass: 157.25,
		category: 'lanthanide',
		row: 8,
		col: 10,
		electronegativity: 1.2,
		density: 7.9,
		melt: 1585,
		boil: 3523,
		discoveryYear: 1880,
		electronConfig: '[Xe] 4f⁷ 5d¹ 6s²',
		summary: 'Ferromagnetic at room temperature; contrast agent in MRI scans.'
	},
	{
		number: 65,
		symbol: 'Tb',
		name: 'Terbium',
		mass: 158.93,
		category: 'lanthanide',
		row: 8,
		col: 11,
		electronegativity: 1.2,
		density: 8.23,
		melt: 1629,
		boil: 3503,
		discoveryYear: 1843,
		electronConfig: '[Xe] 4f⁹ 6s²',
		summary: 'Silvery-white rare earth metal emitting green luminescence.'
	},
	{
		number: 66,
		symbol: 'Dy',
		name: 'Dysprosium',
		mass: 162.5,
		category: 'lanthanide',
		row: 8,
		col: 12,
		electronegativity: 1.22,
		density: 8.54,
		melt: 1680,
		boil: 2840,
		discoveryYear: 1886,
		electronConfig: '[Xe] 4f¹⁰ 6s²',
		summary: 'High magnetic susceptibility; used in nuclear control rods and hard disks.'
	},
	{
		number: 67,
		symbol: 'Ho',
		name: 'Holmium',
		mass: 164.93,
		category: 'lanthanide',
		row: 8,
		col: 13,
		electronegativity: 1.23,
		density: 8.79,
		melt: 1734,
		boil: 2993,
		discoveryYear: 1878,
		electronConfig: '[Xe] 4f¹¹ 6s²',
		summary: 'Possesses the highest magnetic moment of any naturally occurring element.'
	},
	{
		number: 68,
		symbol: 'Er',
		name: 'Erbium',
		mass: 167.26,
		category: 'lanthanide',
		row: 8,
		col: 14,
		electronegativity: 1.24,
		density: 9.066,
		melt: 1802,
		boil: 3141,
		discoveryYear: 1843,
		electronConfig: '[Xe] 4f¹² 6s²',
		summary: 'Pink-colored ion used in optical fiber amplifiers for fiber-optic internet.'
	},
	{
		number: 69,
		symbol: 'Tm',
		name: 'Thulium',
		mass: 168.93,
		category: 'lanthanide',
		row: 8,
		col: 15,
		electronegativity: 1.25,
		density: 9.32,
		melt: 1818,
		boil: 2223,
		discoveryYear: 1879,
		electronConfig: '[Xe] 4f¹³ 6s²',
		summary: 'Least abundant natural lanthanide, used in portable X-ray devices.'
	},
	{
		number: 70,
		symbol: 'Yb',
		name: 'Ytterbium',
		mass: 173.05,
		category: 'lanthanide',
		row: 8,
		col: 16,
		electronegativity: 1.1,
		density: 6.9,
		melt: 1097,
		boil: 1469,
		discoveryYear: 1878,
		electronConfig: '[Xe] 4f¹⁴ 6s²',
		summary: 'Soft metal used in atomic clocks and specialized steel stress gauges.'
	},
	{
		number: 71,
		symbol: 'Lu',
		name: 'Lutetium',
		mass: 174.97,
		category: 'lanthanide',
		row: 8,
		col: 17,
		electronegativity: 1.27,
		density: 9.841,
		melt: 1925,
		boil: 3675,
		discoveryYear: 1907,
		electronConfig: '[Xe] 4f¹⁴ 5d¹ 6s²',
		summary: 'Hardest and densest lanthanide element.'
	},
	{
		number: 72,
		symbol: 'Hf',
		name: 'Hafnium',
		mass: 178.49,
		category: 'transition',
		row: 6,
		col: 4,
		electronegativity: 1.3,
		density: 13.31,
		melt: 2506,
		boil: 4876,
		discoveryYear: 1923,
		electronConfig: '[Xe] 4f¹⁴ 5d² 6s²',
		summary: 'Corrosion-resistant metal chemically identical to zirconium.'
	},
	{
		number: 73,
		symbol: 'Ta',
		name: 'Tantalum',
		mass: 180.95,
		category: 'transition',
		row: 6,
		col: 5,
		electronegativity: 1.5,
		density: 16.69,
		melt: 3290,
		boil: 5731,
		discoveryYear: 1802,
		electronConfig: '[Xe] 4f¹⁴ 5d³ 6s²',
		summary: 'Highly corrosion resistant metal essential for miniature capacitors in electronics.'
	},
	{
		number: 74,
		symbol: 'W',
		name: 'Tungsten',
		mass: 183.84,
		category: 'transition',
		row: 6,
		col: 6,
		electronegativity: 2.36,
		density: 19.25,
		melt: 3695,
		boil: 5828,
		discoveryYear: 1781,
		electronConfig: '[Xe] 4f¹⁴ 5d⁴ 6s²',
		summary: 'Highest melting point of all discovered elements (3422 °C).'
	},
	{
		number: 75,
		symbol: 'Re',
		name: 'Rhenium',
		mass: 186.21,
		category: 'transition',
		row: 6,
		col: 7,
		electronegativity: 1.9,
		density: 21.02,
		melt: 3459,
		boil: 5869,
		discoveryYear: 1925,
		electronConfig: '[Xe] 4f¹⁴ 5d⁵ 6s²',
		summary: "One of the rarest elements in Earth's crust; third highest melting point."
	},
	{
		number: 76,
		symbol: 'Os',
		name: 'Osmium',
		mass: 190.23,
		category: 'transition',
		row: 6,
		col: 8,
		electronegativity: 2.2,
		density: 22.59,
		melt: 3306,
		boil: 5285,
		discoveryYear: 1803,
		electronConfig: '[Xe] 4f¹⁴ 5d⁶ 6s²',
		summary: 'Densest naturally occurring element on Earth.'
	},
	{
		number: 77,
		symbol: 'Ir',
		name: 'Iridium',
		mass: 192.22,
		category: 'transition',
		row: 6,
		col: 9,
		electronegativity: 2.2,
		density: 22.56,
		melt: 2719,
		boil: 4701,
		discoveryYear: 1803,
		electronConfig: '[Xe] 4f¹⁴ 5d⁷ 6s²',
		summary:
			'Most corrosion-resistant metal known; enriched layer marks dinosaur extinction boundary.'
	},
	{
		number: 78,
		symbol: 'Pt',
		name: 'Platinum',
		mass: 195.08,
		category: 'transition',
		row: 6,
		col: 10,
		electronegativity: 2.28,
		density: 21.45,
		melt: 2041.4,
		boil: 4098,
		discoveryYear: 1735,
		electronConfig: '[Xe] 4f¹⁴ 5d⁹ 6s¹',
		summary: 'Dense, malleable, highly unreactive noble metal used in catalytic converters.'
	},
	{
		number: 79,
		symbol: 'Au',
		name: 'Gold',
		mass: 196.97,
		category: 'transition',
		row: 6,
		col: 11,
		electronegativity: 2.54,
		density: 19.3,
		melt: 1337.33,
		boil: 3129,
		discoveryYear: 'Ancient',
		electronConfig: '[Xe] 4f¹⁴ 5d¹⁰ 6s¹',
		summary: 'Bright, slightly reddish yellow, dense, soft, malleable noble metal.'
	},
	{
		number: 80,
		symbol: 'Hg',
		name: 'Mercury',
		mass: 200.59,
		category: 'transition',
		row: 6,
		col: 12,
		electronegativity: 2.0,
		density: 13.534,
		melt: 234.32,
		boil: 629.88,
		discoveryYear: 'Ancient',
		electronConfig: '[Xe] 4f¹⁴ 5d¹⁰ 6s²',
		summary:
			'Only metallic element that is liquid at standard conditions for temperature and pressure.'
	},
	{
		number: 81,
		symbol: 'Tl',
		name: 'Thallium',
		mass: 204.38,
		category: 'post-transition',
		row: 6,
		col: 13,
		electronegativity: 1.62,
		density: 11.85,
		melt: 577,
		boil: 1746,
		discoveryYear: 1861,
		electronConfig: '[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p¹',
		summary: "Extremely toxic grey post-transition metal historically nicknamed poisoner's poison."
	},
	{
		number: 82,
		symbol: 'Pb',
		name: 'Lead',
		mass: 207.2,
		category: 'post-transition',
		row: 6,
		col: 14,
		electronegativity: 1.87,
		density: 11.34,
		melt: 600.61,
		boil: 2022,
		discoveryYear: 'Ancient',
		electronConfig: '[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p²',
		summary: 'Heavy metal denser than most common materials; soft and malleable.'
	},
	{
		number: 83,
		symbol: 'Bi',
		name: 'Bismuth',
		mass: 208.98,
		category: 'post-transition',
		row: 6,
		col: 15,
		electronegativity: 2.02,
		density: 9.78,
		melt: 544.7,
		boil: 1837,
		discoveryYear: 1753,
		electronConfig: '[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p³',
		summary: 'High diamagnetism and iridescent oxidation surface layer.'
	},
	{
		number: 84,
		symbol: 'Po',
		name: 'Polonium',
		mass: 209,
		category: 'post-transition',
		row: 6,
		col: 16,
		electronegativity: 2.0,
		density: 9.196,
		melt: 527,
		boil: 1235,
		discoveryYear: 1898,
		electronConfig: '[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁴',
		summary: 'Rare and highly radioactive metal discovered by Marie and Pierre Curie.'
	},
	{
		number: 85,
		symbol: 'At',
		name: 'Astatine',
		mass: 210,
		category: 'metalloid',
		row: 6,
		col: 17,
		electronegativity: 2.2,
		density: 7,
		melt: 575,
		boil: 610,
		discoveryYear: 1940,
		electronConfig: '[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁵',
		summary: "Rarest naturally occurring element in Earth's crust."
	},
	{
		number: 86,
		symbol: 'Rn',
		name: 'Radon',
		mass: 222,
		category: 'noble-gas',
		row: 6,
		col: 18,
		electronegativity: 2.2,
		density: 0.00973,
		melt: 202,
		boil: 211.5,
		discoveryYear: 1899,
		electronConfig: '[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁶',
		summary: 'Radioactive, colorless, odorless noble gas produced by radium decay.'
	},
	{
		number: 87,
		symbol: 'Fr',
		name: 'Francium',
		mass: 223,
		category: 'alkali-metal',
		row: 7,
		col: 1,
		electronegativity: 0.79,
		density: 1.87,
		melt: 300,
		boil: 950,
		discoveryYear: 1939,
		electronConfig: '[Rn] 7s¹',
		summary: "Extremely radioactive alkali metal; second-rarest element in Earth's crust."
	},
	{
		number: 88,
		symbol: 'Ra',
		name: 'Radium',
		mass: 226,
		category: 'alkaline-earth',
		row: 7,
		col: 2,
		electronegativity: 0.9,
		density: 5.5,
		melt: 973,
		boil: 2010,
		discoveryYear: 1898,
		electronConfig: '[Rn] 7s²',
		summary: 'Intensely radioactive alkaline earth metal that glows faint blue.'
	},
	{
		number: 89,
		symbol: 'Ac',
		name: 'Actinium',
		mass: 227,
		category: 'actinide',
		row: 9,
		col: 3,
		electronegativity: 1.1,
		density: 10.07,
		melt: 1323,
		boil: 3473,
		discoveryYear: 1899,
		electronConfig: '[Rn] 6d¹ 7s²',
		summary: 'Silvery-white radioactive metallic element giving name to actinides.'
	},
	{
		number: 90,
		symbol: 'Th',
		name: 'Thorium',
		mass: 232.04,
		category: 'actinide',
		row: 9,
		col: 4,
		electronegativity: 1.3,
		density: 11.72,
		melt: 2023,
		boil: 5061,
		discoveryYear: 1829,
		electronConfig: '[Rn] 6d² 7s²',
		summary: 'Weakly radioactive metal considered as alternative nuclear fuel.'
	},
	{
		number: 91,
		symbol: 'Pa',
		name: 'Protactinium',
		mass: 231.04,
		category: 'actinide',
		row: 9,
		col: 5,
		electronegativity: 1.5,
		density: 15.37,
		melt: 1841,
		boil: 4300,
		discoveryYear: 1913,
		electronConfig: '[Rn] 5f² 6d¹ 7s²',
		summary: 'Dense, silvery-gray radioactive actinide.'
	},
	{
		number: 92,
		symbol: 'U',
		name: 'Uranium',
		mass: 238.03,
		category: 'actinide',
		row: 9,
		col: 6,
		electronegativity: 1.38,
		density: 19.1,
		melt: 1405.3,
		boil: 4404,
		discoveryYear: 1789,
		electronConfig: '[Rn] 5f³ 6d¹ 7s²',
		summary: 'Heavy actinide metal providing primary fuel for nuclear reactors.'
	},
	{
		number: 93,
		symbol: 'Np',
		name: 'Neptunium',
		mass: 237,
		category: 'actinide',
		row: 9,
		col: 7,
		electronegativity: 1.36,
		density: 20.45,
		melt: 912,
		boil: 4273,
		discoveryYear: 1940,
		electronConfig: '[Rn] 5f⁴ 6d¹ 7s²',
		summary: 'First transuranic element synthesized artificially.'
	},
	{
		number: 94,
		symbol: 'Pu',
		name: 'Plutonium',
		mass: 244,
		category: 'actinide',
		row: 9,
		col: 8,
		electronegativity: 1.28,
		density: 19.816,
		melt: 912.5,
		boil: 3505,
		discoveryYear: 1940,
		electronConfig: '[Rn] 5f⁶ 7s²',
		summary: 'Radioactive transuranic element used in nuclear weapons and space probes.'
	},
	{
		number: 95,
		symbol: 'Am',
		name: 'Americium',
		mass: 243,
		category: 'actinide',
		row: 9,
		col: 9,
		electronegativity: 1.3,
		density: 12,
		melt: 1449,
		boil: 2880,
		discoveryYear: 1944,
		electronConfig: '[Rn] 5f⁷ 7s²',
		summary: 'Synthetic actinide widely used in household ionization smoke detectors.'
	},
	{
		number: 96,
		symbol: 'Cm',
		name: 'Curium',
		mass: 247,
		category: 'actinide',
		row: 9,
		col: 10,
		electronegativity: 1.3,
		density: 13.51,
		melt: 1613,
		boil: 3383,
		discoveryYear: 1944,
		electronConfig: '[Rn] 5f⁷ 6d¹ 7s²',
		summary: 'Named after Marie and Pierre Curie; strong alpha emitter.'
	},
	{
		number: 97,
		symbol: 'Bk',
		name: 'Berkelium',
		mass: 247,
		category: 'actinide',
		row: 9,
		col: 11,
		electronegativity: 1.3,
		density: 14.78,
		melt: 1259,
		boil: 2900,
		discoveryYear: 1949,
		electronConfig: '[Rn] 5f⁹ 7s²',
		summary: 'Synthetic radioactive element produced in microgram quantities.'
	},
	{
		number: 98,
		symbol: 'Cf',
		name: 'Californium',
		mass: 251,
		category: 'actinide',
		row: 9,
		col: 12,
		electronegativity: 1.3,
		density: 15.1,
		melt: 1173,
		boil: 1743,
		discoveryYear: 1950,
		electronConfig: '[Rn] 5f¹⁰ 7s²',
		summary: 'Strong neutron emitter used to start nuclear reactors and inspect materials.'
	},
	{
		number: 99,
		symbol: 'Es',
		name: 'Einsteinium',
		mass: 252,
		category: 'actinide',
		row: 9,
		col: 13,
		electronegativity: 1.3,
		density: 8.84,
		melt: 1133,
		boil: 1269,
		discoveryYear: 1952,
		electronConfig: '[Rn] 5f¹¹ 7s²',
		summary: 'Discovered in debris of the Ivy Mike thermonuclear bomb test.'
	},
	{
		number: 100,
		symbol: 'Fm',
		name: 'Fermium',
		mass: 257,
		category: 'actinide',
		row: 9,
		col: 14,
		electronegativity: 1.3,
		density: null,
		melt: 1800,
		boil: null,
		discoveryYear: 1952,
		electronConfig: '[Rn] 5f¹² 7s²',
		summary: 'Heaviest element that can be formed by neutron bombardment of lighter elements.'
	},
	{
		number: 101,
		symbol: 'Md',
		name: 'Mendelevium',
		mass: 258,
		category: 'actinide',
		row: 9,
		col: 15,
		electronegativity: 1.3,
		density: null,
		melt: 1100,
		boil: null,
		discoveryYear: 1955,
		electronConfig: '[Rn] 5f¹³ 7s²',
		summary: 'Named in honor of Dmitri Mendeleev, father of the periodic table.'
	},
	{
		number: 102,
		symbol: 'No',
		name: 'Nobelium',
		mass: 259,
		category: 'actinide',
		row: 9,
		col: 16,
		electronegativity: 1.3,
		density: null,
		melt: 1100,
		boil: null,
		discoveryYear: 1966,
		electronConfig: '[Rn] 5f¹⁴ 7s²',
		summary: 'Synthetic radioactive element named after Alfred Nobel.'
	},
	{
		number: 103,
		symbol: 'Lr',
		name: 'Lawrencium',
		mass: 266,
		category: 'actinide',
		row: 9,
		col: 17,
		electronegativity: 1.3,
		density: null,
		melt: 1900,
		boil: null,
		discoveryYear: 1961,
		electronConfig: '[Rn] 5f¹⁴ 6d¹ 7s²',
		summary: 'Final actinide element, named after cyclotron inventor Ernest Lawrence.'
	},
	{
		number: 104,
		symbol: 'Rf',
		name: 'Rutherfordium',
		mass: 267,
		category: 'transition',
		row: 7,
		col: 4,
		electronegativity: null,
		density: 23.2,
		melt: 2400,
		boil: 5800,
		discoveryYear: 1969,
		electronConfig: '[Rn] 5f¹⁴ 6d² 7s²',
		summary: 'Superheavy synthetic element named after Ernest Rutherford.'
	},
	{
		number: 105,
		symbol: 'Db',
		name: 'Dubnium',
		mass: 268,
		category: 'transition',
		row: 7,
		col: 5,
		electronegativity: null,
		density: 29.3,
		melt: null,
		boil: null,
		discoveryYear: 1970,
		electronConfig: '[Rn] 5f¹⁴ 6d³ 7s²',
		summary: 'Highly radioactive element named after Dubna, Russia.'
	},
	{
		number: 106,
		symbol: 'Sg',
		name: 'Seaborgium',
		mass: 269,
		category: 'transition',
		row: 7,
		col: 6,
		electronegativity: null,
		density: 35.0,
		melt: null,
		boil: null,
		discoveryYear: 1974,
		electronConfig: '[Rn] 5f¹⁴ 6d⁴ 7s²',
		summary: 'Named after Glenn T. Seaborg.'
	},
	{
		number: 107,
		symbol: 'Bh',
		name: 'Bohrium',
		mass: 270,
		category: 'transition',
		row: 7,
		col: 7,
		electronegativity: null,
		density: 37.1,
		melt: null,
		boil: null,
		discoveryYear: 1981,
		electronConfig: '[Rn] 5f¹⁴ 6d⁵ 7s²',
		summary: 'Named in honor of Danish physicist Niels Bohr.'
	},
	{
		number: 108,
		symbol: 'Hs',
		name: 'Hassium',
		mass: 277,
		category: 'transition',
		row: 7,
		col: 8,
		electronegativity: null,
		density: 40.7,
		melt: null,
		boil: null,
		discoveryYear: 1984,
		electronConfig: '[Rn] 5f¹⁴ 6d⁶ 7s²',
		summary: 'Superheavy element named after German state of Hesse.'
	},
	{
		number: 109,
		symbol: 'Mt',
		name: 'Meitnerium',
		mass: 278,
		category: 'unknown',
		row: 7,
		col: 9,
		electronegativity: null,
		density: 37.4,
		melt: null,
		boil: null,
		discoveryYear: 1982,
		electronConfig: '[Rn] 5f¹⁴ 6d⁷ 7s²',
		summary: 'Named after Austrian-Swedish physicist Lise Meitner.'
	},
	{
		number: 110,
		symbol: 'Ds',
		name: 'Darmstadtium',
		mass: 281,
		category: 'unknown',
		row: 7,
		col: 10,
		electronegativity: null,
		density: 34.8,
		melt: null,
		boil: null,
		discoveryYear: 1994,
		electronConfig: '[Rn] 5f¹⁴ 6d⁸ 7s²',
		summary: 'Discovered near Darmstadt, Germany.'
	},
	{
		number: 111,
		symbol: 'Rg',
		name: 'Roentgenium',
		mass: 282,
		category: 'unknown',
		row: 7,
		col: 11,
		electronegativity: null,
		density: 28.7,
		melt: null,
		boil: null,
		discoveryYear: 1994,
		electronConfig: '[Rn] 5f¹⁴ 6d⁹ 7s²',
		summary: 'Named after Wilhelm Röntgen, discoverer of X-rays.'
	},
	{
		number: 112,
		symbol: 'Cn',
		name: 'Copernicium',
		mass: 285,
		category: 'transition',
		row: 7,
		col: 12,
		electronegativity: null,
		density: 23.7,
		melt: null,
		boil: 357,
		discoveryYear: 1996,
		electronConfig: '[Rn] 5f¹⁴ 6d¹⁰ 7s²',
		summary: 'Named after astronomer Nicolaus Copernicus.'
	},
	{
		number: 113,
		symbol: 'Nh',
		name: 'Nihonium',
		mass: 286,
		category: 'unknown',
		row: 7,
		col: 13,
		electronegativity: null,
		density: 16,
		melt: 700,
		boil: 1400,
		discoveryYear: 2004,
		electronConfig: '[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p¹',
		summary: 'First element synthesized in an Asian country (Japan).'
	},
	{
		number: 114,
		symbol: 'Fl',
		name: 'Flerovium',
		mass: 289,
		category: 'post-transition',
		row: 7,
		col: 14,
		electronegativity: null,
		density: 14,
		melt: 340,
		boil: 420,
		discoveryYear: 1998,
		electronConfig: '[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p²',
		summary: 'Extremely radioactive synthetic element.'
	},
	{
		number: 115,
		symbol: 'Mc',
		name: 'Moscovium',
		mass: 290,
		category: 'unknown',
		row: 7,
		col: 15,
		electronegativity: null,
		density: 13.5,
		melt: 670,
		boil: 1400,
		discoveryYear: 2003,
		electronConfig: '[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p³',
		summary: 'Synthesized by joint team of Russian and American scientists.'
	},
	{
		number: 116,
		symbol: 'Lv',
		name: 'Livermorium',
		mass: 293,
		category: 'unknown',
		row: 7,
		col: 16,
		electronegativity: null,
		density: 12.9,
		melt: 708,
		boil: 1085,
		discoveryYear: 2000,
		electronConfig: '[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁴',
		summary: 'Named after Lawrence Livermore National Laboratory.'
	},
	{
		number: 117,
		symbol: 'Ts',
		name: 'Tennessine',
		mass: 294,
		category: 'unknown',
		row: 7,
		col: 17,
		electronegativity: null,
		density: 7.2,
		melt: 723,
		boil: 883,
		discoveryYear: 2010,
		electronConfig: '[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁵',
		summary: 'Second-heaviest known chemical element.'
	},
	{
		number: 118,
		symbol: 'Og',
		name: 'Oganesson',
		mass: 294,
		category: 'unknown',
		row: 7,
		col: 18,
		electronegativity: null,
		density: 5.0,
		melt: 325,
		boil: 350,
		discoveryYear: 2002,
		electronConfig: '[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁶',
		summary: 'Highest atomic number and atomic mass of all elements discovered so far.'
	}
];
