const appList = [
    { title: 'About', icon: '👤', path: '../about/index.html' },
    { title: 'Authenticator', icon: '🔐', path: '../authenticator/index.html' },
    { title: 'Blocks', icon: '🧱', path: '../blocks/index.html' },
    { title: 'Calculator', icon: '🔢', path: '../calculator/index.html' },
    { title: 'Camera', icon: '📷', path: '../camera/index.html' },
    { title: 'Charts', icon: '📊', path: '../charts/index.html' },
    { title: 'Chat', icon: '💬', path: '../chat/index.html' },
    { title: 'Chess', icon: '♟️', path: '../chess/index.html' },
    { title: 'Clock', icon: '⏰', path: '../clock/index.html'},
    { title: 'Converter', icon: '➡️', path: '../converter/index.html' },
    { title: 'Documents', icon: '📜', path: '../documents/index.html' },
    { title: 'Encrypt', icon: '🔑', path: '../encrypt/index.html' },
    { title: 'Fallpiece', icon: '🧩', path: '../fallpiece/index.html' },
    { title: 'Files', icon: '📁', path: '../files/index.html' },
    { title: 'Gallery', icon: '🖼️', path: '../gallery/index.html' },
    { title: 'Hop', icon: '🦘', path: '../hop/index.html' },
    { title: 'Info', icon: 'ℹ️', path: '../info/index.html' },
    { title: 'Jump', icon: '⏫', path: '../jump/index.html' },
    { title: 'Links', icon: '🔗', path: '../links/index.html' },
    { title: 'Maps', icon: '🗺️', path: '../maps/index.html' },
    { title: 'Merge', icon: '🔀', path: '../merge/index.html' },
    { title: 'News', icon: '📰', path: '../news/index.html' },
    { title: 'Notepad', icon: '📝', path: '../notepad/index.html' },
    { title: 'Paint', icon: '🎨', path: '../paint/index.html' },
    { title: 'Player', icon: '🎬', path: '../player/index.html' },
    { title: 'Pong', icon: '🏓', path: '../pong/index.html' },
    { title: 'Presentations', icon: '📑', path: '../presentations/index.html' },
    { title: 'Qr', icon: '🔳', path: '../qr/index.html' },
    { title: 'Quizzes', icon: '❓', path: '../quizzes/index.html' },
    { title: 'Randomize', icon: '🎲', path: '../randomize/index.html' },
    { title: 'Recorder', icon: '🎥', path: '../recorder/index.html' },
    { title: 'Send', icon: '📥', path: '../send/index.html' },
    { title: 'Snake', icon: '🐍', path: '../snake/index.html' },
    { title: 'Soundboard', icon: '🔊', path: '../soundboard/index.html' },
    { title: 'Spreadsheets', icon: '🧮', path: '../spreadsheets/index.html' },
    { title: 'Synthesizer', icon: '🎹', path: '../synthesizer/index.html' },
    { title: 'Tictactoe', icon: '🌀', path: '../tictactoe/index.html'},
    { title: 'Translate', icon: '🌐', path: '../translate/index.html' },
    { title: 'Weather', icon: '⛅', path: '../weather/index.html'},
];
// { title: '', icon: '', path: '../?/index.html'},
